#!/bin/bash

while IFS='' read -r line || [[ -n "$line" ]]; do
	test=`curl -L $line | grep "100% off"`
	if [ "$test" != "" ]; then
		echo $line >> ../Result/list_free.txt
	fi
done < urls_code.txt
rm urls_code.txt

exit 0
