#!/bin/bash

if [ ! -f ../Result/ancien_urls.txt ]; then
	echo "Fichier ancien_urls.txt manquant dans le dossier Result du projet !" && sleep 5
	exit 1
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
	coupon=`echo "$line" | cut -d"=" -f2`
	prof=`curl -L $line | grep -m 1 'href="/user/' | grep -o 'user/[[:alnum:]+\.\_\-]*'`
	test1=`cat list_prof.txt | grep $prof`
	if [ "$test1" != "" ]; then
		continue
	else
		echo "$prof" >> list_prof.txt
	fi
	for i in {1..5}
	do
		for id in `curl -L https://www.udemy.com/$prof/?taught_courses=$i | grep -o 'data-courseid="[[:alnum:]+\.\_\-]*"' | cut -d"=" -f2 | sed 's/"//g'`
		do
			test2=`curl -L https://www.udemy.com/$id/?couponCode=$coupon | grep "100% off"`
			if [ "$test2" != "" ]; then
				echo "https://www.udemy.com/$id/?couponCode=$coupon" >> ../Result/bruteforce_list.txt
			fi
		done
	done
done < ../Result/ancien_urls.txt
rm list_prof.txt

exit 0
