#!/bin/bash

cat ../Result/bruteforce_list.txt | sort | uniq -i > ../Result/bruteforce_list_temp.txt
mv -f ../Result/bruteforce_list_temp.txt ../Result/bruteforce_list.txt

while IFS='' read -r line || [[ -n "$line" ]]; do
	coupon=`echo "$line" | cut -d"=" -f2`
	url=`curl -L "$line" | grep -m 1 'property="og:url" content' | grep -o 'https://www.udemy.com/[[:alnum:]+\.\_\-]*/'`
	echo "$url?couponCode=$coupon" >> ../Result/bruteforce_list_temp.txt
done < ../Result/bruteforce_list.txt
rm ../Result/bruteforce_list.txt

cat ../Result/bruteforce_list_temp.txt | sort | uniq -i > ../Result/bruteforce_list.txt
rm ../Result/bruteforce_list_temp.txt

diff ../Result/bruteforce_list.txt ../Result/ancien_urls.txt | grep "^<" | cut -d" " -f2 >> ../Result/bruteforce_urls.txt
rm ../Result/bruteforce_list.txt

cat ../Result/bruteforce_urls.txt >> ../Result/ancien_urls.txt
cat ../Result/bruteforce_urls.txt >> ../Checkout/add_list.txt
rm ../Result/bruteforce_urls.txt

cat ../Checkout/add_list.txt | sort | uniq -i > ../Checkout/add_list_temp.txt
mv -f ../Checkout/add_list_temp.txt ../Checkout/add_list.txt

cat ../Result/ancien_urls.txt | sort | uniq -i > ../Result/ancien_urls_temp.txt
mv -f ../Result/ancien_urls_temp.txt ../Result/ancien_urls.txt

exit 0
