#!/bin/bash

if [ "$1" == "" ]; then
	fichier=`zenity --file-selection --title "Verificate Coupons List :"`
	sortie=`zenity --file-selection --save --title "Verificate Coupons List :"`
else
	fichier="$1"
	sortie="$2"
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
	titre=`wget -qO- "$line" | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si' | cut -d"|" -f1`
	echo "$titre : $line" | sed 's/&amp//g' >> "$sortie"
done < "$fichier"

exit 0
