#!/bin/bash

if [ "$1" == "" ]; then
	fichier=`zenity --file-selection --title "Verificate Coupons List :"`
	sortie=`zenity --file-selection --save --title "Verificate Coupons List :"`
else
	fichier="$1"
	sortie="$2"
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
	test=`curl -L $line | grep "100% off"`
	if [ "$test" != "" ]; then
		echo $line >> "$sortie"-temp.txt
	fi
done < "$fichier"

cat "$sortie"-temp.txt | sort | uniq -i > "$sortie"
rm "$sortie"-temp.txt

exit 0
